{
 "title": "Alloy and Loki Dashboard",
 "description": "Dashboard for Rasperry Pi Logs with Alloy and Loki",
 "tags": [
  "loki",
  "logs",
  "promtail"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Datenquelle", "query": "loki" },
   { "name": "filter", "label": "Filter" },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DEBUG Logs",
   "type": "stat",
   "description": "Number of DEBUG log messages",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"(?i)\\\\b(debug)\\\\b\" | label_format detected_level=\"debug\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "INFO Logs",
   "type": "stat",
   "description": "Number of INFO log messages",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"(?i)\\\\b(info|notice)\\\\b\" | label_format detected_level=\"info\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "WARN Logs",
   "type": "stat",
   "description": "Number of WARN log messages",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"(?i)\\\\b(warn|warning)\\\\b\" | label_format detected_level=\"warn\" [$__range]))"
    }
   ]
  },
  {
   "title": "ERROR Logs",
   "type": "stat",
   "description": "Number of ERROR log messages",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} | logfmt |~ \"(?i)\\\\b(error|fail|critical|crit|fatal)\\\\b\" | label_format detected_level=\"error\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "stat",
   "description": "Total number of log messages",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=\"$host\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Warnings, Errors, Infos, Debugs, Fatals, and Traces  over time",
   "type": "timeseries",
   "description": "Warnings, Errors, Infos, Debugs, Fatals, and Traces  over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"\\\\b(?i)(warn|warning)\\\\b\"| label_format detected_level=\"warn\" | __error__=\"\" [$__range]))",
     "legendFormat": "Warning"
    },
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"(?i)\\\\b(error|fail|critical|crit|fatal)\\\\b\" | label_format detected_level=\"error\" | __error__=\"\" [$__range]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"\\\\b(?i)(info)\\\\b\"| label_format detected_level=\"info\" | __error__=\"\" [$__range]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"\\\\b(?i)(debug)\\\\b\"| label_format detected_level=\"debug\" | __error__=\"\" [$__range]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"\\\\b(?i)(fatal)\\\\b\"| label_format detected_level=\"fatal\" | __error__=\"\" [$__range]))",
     "legendFormat": "Fatal"
    },
    {
     "expr": "sum by (detected_level) (count_over_time({hostname=\"$host\"} |~ \"\\\\b(?i)(trace)\\\\b\"| label_format detected_level=\"trace\" | __error__=\"\" [$__range]))",
     "legendFormat": "Trace"
    }
   ]
  },
  {
   "title": "Logs sorted by severity",
   "type": "logs",
   "description": "Displaying logs by severity",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=\"$host\"} |~ \"(?i)\\\\b(debug)\\\\b\" | label_format detected_level=\"debug\" |= \"$filter\" | line_format `🔵 {{regexReplaceAll \"level=debug|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim  }}`"
    },
    {
     "direction": "backward",
     "expr": "{hostname=\"$host\"}|~ \"(?i)\\\\b(info|notice)\\\\b\" | label_format detected_level=\"info\" |= \"$filter\" | line_format `🟢 {{regexReplaceAll \"level=info|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim }}`"
    },
    {
     "direction": "backward",
     "expr": "{hostname=\"$host\"} |~ \"(?i)\\\\b(warn|warning)\\\\b\" | label_format detected_level=\"warn\" |= \"$filter\" | line_format `🟡 {{regexReplaceAll \"level=warn|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim  }}`"
    },
    {
     "direction": "backward",
     "expr": "{hostname=\"$host\"} \r\n|~ \"(?i)\\\\b(error|fail|critical|crit|fatal)\\\\b\" \r\n| label_format detected_level=\"error\" \r\n|= \"$filter\" \r\n| line_format `🔴 {{regexReplaceAll \"level=error|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim  }}`\r\n"
    },
    {
     "expr": "{hostname=\"$host\"} |~ \"(?i)\\\\b(fatal)\\\\b\" | label_format detected_level=\"fatal\" |= \"$filter\" | line_format `🟠 {{regexReplaceAll \"level=fatal|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim  }}`"
    },
    {
     "expr": "{hostname=\"$host\"} |~ \"(?i)\\\\b(trace)\\\\b\" | label_format detected_level=\"trace\" |= \"$filter\" | line_format `🟣 {{regexReplaceAll \"level=trace|ts=[^\\\\s]+\\\\s\" __line__ \"\" | trim  }}`"
    }
   ]
  }
 ]
}